#! /usr/bin/env bash

hephaestus_command=$1
hephaestus_file=$2

run="ruby $HOME/Playground/Compiladores/walnut/compiler/main.rb $PWD/$walnut_file"

run_file() {
  echo "Compiling $hephaestus_file"
  $run
}

die() {
  echo "$1"
  exit
}

if [ "$hephaestus_command" == "run" ]; then
  if [ ! -f $hephaestus file ]; then
    die '$hephaestus_file not found'
  else
    run_file
    die
  fi
fi
