#! /usr/bin/env bash

hephaestus_command=$1
hephaestus_file=$2

run="ruby $HOME/.hephaestus/main.rb $PWD/Tests/$hephaestus_file"

run_file() {
  echo "Compiling $hephaestus_file"
  $run
}

die() {
  echo "$1"
  exit
}

if [ "$hephaestus_command" == "run" ]; then
  if [ echo "gem list antlr3 -i"]; then
    if [ -e "$PWD/Tests/$hephaestus_file" ]; then
      run_file
      die
    else
      die 'Hephaestus file not found.'
    fi
  else
    echo "Installing antlr3"
    eval gem install antlr3
    echo "Antlr is now installed, try to run again."
  fi
fi
